apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "color-webapp.fullname" . }}-{{ .Values.color }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "color-webapp.name" . }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ include "color-webapp.name" . }}
        color: {{ .Values.color }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
